### ISSUE TITLE
As a user, I can search the website

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA-TTS/identity-dev-docs#200]
As part of GSA's Web Modernization efforts, websites are being evaluated per guidance in the [21st Century IDEA](https://digital.gov/resources/21st-century-integrated-digital-experience-act/).

Part of that guidance calls for search ([for example](https://search.gov/)) on public content. More information can be found here: https://github.com/GSA/wg-web-modernization/issues/15.

Happy to chat more.

**Comment by Ppmahadevan** [comment]
Thanking you for my India and US

**Comment by aduth** [comment]
A search feature has been implemented as of #359 (cc @Sgtpluck )
